In [85]:
import numpy as np 
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [86]:
arr = np.arange(1,31).reshape(6,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [87]:
print(arr[0:,3])

[ 4  9 14 19 24 29]


In [88]:
arr = np.arange(11,21)

In [89]:
bool_index =  arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [90]:
arr = arr[bool_index]
print(arr)

[12 14 16 18 20]


In [91]:
arr = np.arange(1,26).reshape(5,5)

In [92]:
brr=np.arange(26,51).reshape(5,5)

In [93]:
arr@brr

array([[ 590,  605,  620,  635,  650],
       [1490, 1530, 1570, 1610, 1650],
       [2390, 2455, 2520, 2585, 2650],
       [3290, 3380, 3470, 3560, 3650],
       [4190, 4305, 4420, 4535, 4650]])

In [94]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])



In [95]:
for i in range(0,9,3):
    for j in range(0,9,3):
        print(s[i:i+3,j:j+3])
        n= s[i:i+3,j:j+3]
        print(n.sum())

[[5 3 4]
 [6 7 2]
 [1 9 8]]
45
[[6 7 8]
 [1 9 5]
 [3 4 2]]
45
[[9 1 2]
 [3 4 8]
 [5 6 7]]
45
[[8 5 9]
 [4 2 6]
 [7 1 3]]
45
[[7 6 1]
 [8 5 3]
 [9 2 4]]
45
[[4 2 3]
 [7 9 1]
 [8 5 6]]
45
[[9 6 1]
 [2 8 7]
 [3 4 5]]
45
[[5 3 7]
 [4 1 9]
 [2 8 6]]
45
[[2 8 4]
 [6 3 5]
 [1 7 9]]
45


In [96]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [97]:
#Get the shape of the matrix.

data.shape

(5, 3)

In [98]:
#Find the average age of students.
print(np.mean(data[:,0]))

18.4


In [99]:
#Extract Math marks of all students.

print(data[:,1])

[85 92 76 65 90]


In [100]:
#Find the highest Science mark.

print(max(data[:,2]))

95


In [101]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1]>90]

array([[19, 92, 88]])

In [102]:
# data[:,1]+=5
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [103]:
len(data[data[:,0]<19])

3

In [104]:
data[:,1:]

array([[85, 78],
       [92, 88],
       [76, 95],
       [65, 70],
       [90, 85]])

In [105]:
np.mean(data[:,1:],axis=0)

array([81.6, 83.2])

In [113]:
print(data[(data[:,1]>=80 )&( data[:,2]>=80)])

[[19 92 88]
 [20 90 85]]


In [111]:
data[:,2][data[:,2]<75]=0

In [112]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])